const REMOVE_ITEM = "REMOVE_ITEM";
const SUCCESS_ITEMS = "SUCCESS_ITEMS";
const HIDDEN_ITEM = "HIDDEN_ITEM";
const CLOSE_ITEMS = "CLOSE_ITEMS";
const OPTION_ITEMS = "OPTION_ITEMS";

export { SUCCESS_ITEMS, REMOVE_ITEM, HIDDEN_ITEM, CLOSE_ITEMS, OPTION_ITEMS };
