const REMOVE_ITEM = "REMOVE_ITEM";
const SUCCESS_ITEMS = "SUCCESS_ITEMS";
const OPEN_ITEM = "OPEN_ITEM";
const CLOSE_ITEMS = "CLOSE_ITEMS";
const OPTION_ITEMS = "OPTION_ITEMS";

export { SUCCESS_ITEMS, REMOVE_ITEM, OPEN_ITEM, CLOSE_ITEMS, OPTION_ITEMS };
