const REMOVE_ITEM = "REMOVE_ITEM";
const SUCCESS_ITEMS = "SUCCESS_ITEMS";
const OPEN_LIST = "OPEN_ITEM";
const OPEN_ITEMS = "CLOSE_ITEMS";
const OPTION_ITEMS = "OPTION_ITEMS";

export { SUCCESS_ITEMS, REMOVE_ITEM, OPEN_LIST, OPEN_ITEMS, OPTION_ITEMS };
